version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./config:/config
    networks:
      - webnet

  redis:
    image: "redis:alpine"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet:
