# config/config.yaml
rate_limit: 100                    # Максимальное количество запросов от одного IP за указанный период
time_window: 60                    # Период в секундах для ограничения запросов
allowed_origins:                   # Разрешенные домены для CORS
  - "https://example.com"
log_file: "/var/log/app/blocked_requests.log"  # Путь к файлу логирования заблокированных запросов
